Logging started at 2016-12-14 11:35:39
File name: C:\Users\jerem\Desktop\Project Reality RSPS\Project Reality\.\data\logs\err\1481744139106 - jerem - [Wed Dec 14][11.35AM].txt
System.getProperty("os.name"): "Windows 10"

[2016-12-14 20:05:27] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'sql5148466.hs_users' doesn't exist
[2016-12-14 20:05:27] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2016-12-14 20:05:27] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[2016-12-14 20:05:27] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2016-12-14 20:05:27] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2016-12-14 20:05:28] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2016-12-14 20:05:28] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2016-12-14 20:05:28] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2016-12-14 20:05:28] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2016-12-14 20:05:28] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2016-12-14 20:05:28] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2016-12-14 20:05:28] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2016-12-14 20:05:28] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2016-12-14 20:05:28] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2016-12-14 20:05:28] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2016-12-14 20:05:28] 	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1021)
[2016-12-14 20:05:28] 	at com.vencillio.core.network.mysql.impl.Highscores.run(Highscores.java:38)
[2016-12-14 20:05:28] 	at java.lang.Thread.run(Unknown Source)
