Logging started at 2017-09-19 17:53:05
File name: C:\Users\Tyras\Desktop\MAIN SERVER (Vencillio Source)\Tyras Source\.\data\logs\err\1505839985685 - Tyras - [Tue Sep 19][5.53PM].txt
System.getProperty("os.name"): "Windows 10"

[2017-09-19 18:42:34] Failing to update test highscores. Database could not connect.
[2017-09-19 18:44:34] Failing to update Test highscores. Database could not connect.
[2017-09-19 18:45:35] Failing to update Test highscores. Database could not connect.
[2017-09-19 18:48:58] Failing to update Perm highscores. Database could not connect.
[2017-09-19 19:08:34] Failing to update Boop highscores. Database could not connect.
[2017-09-19 21:05:33] Failing to update Mex highscores. Database could not connect.
[2017-09-19 21:37:56] Failing to update Oe highscores. Database could not connect.
[2017-09-19 22:01:42] Failing to update Boop highscores. Database could not connect.
[2017-09-19 22:02:40] Failing to update Dk Is King highscores. Database could not connect.
[2017-09-19 22:04:57] Failing to update Dk Is King highscores. Database could not connect.
[2017-09-19 22:08:16] Failing to update Dk Is King highscores. Database could not connect.
[2017-09-19 22:13:58] Failing to update Dk Is King highscores. Database could not connect.
[2017-09-19 22:24:02] Failing to update Dk Is King highscores. Database could not connect.
[2017-09-19 22:36:25] Failing to update Zezima highscores. Database could not connect.
[2017-09-19 23:05:51] Failing to update Perm highscores. Database could not connect.
[2017-09-19 23:08:48] Failing to update Oe highscores. Database could not connect.
[2017-09-20 01:19:41] java.lang.ArrayIndexOutOfBoundsException: 0
[2017-09-20 01:19:41] 	at com.vencillio.core.util.Utility.randomElement(Utility.java:638)
[2017-09-20 01:19:41] 	at com.vencillio.rs2.content.CrystalChest.searchChest(CrystalChest.java:97)
[2017-09-20 01:19:41] 	at com.vencillio.rs2.entity.WalkToActions.finishObjectClick(WalkToActions.java:1860)
[2017-09-20 01:19:41] 	at com.vencillio.rs2.entity.WalkToActions$7.onDestination(WalkToActions.java:311)
[2017-09-20 01:19:41] 	at com.vencillio.core.task.impl.WalkToTask.execute(WalkToTask.java:39)
[2017-09-20 01:19:41] 	at com.vencillio.core.task.TaskQueue.queue(TaskQueue.java:117)
[2017-09-20 01:19:41] 	at com.vencillio.rs2.entity.WalkToActions.clickObject(WalkToActions.java:306)
[2017-09-20 01:19:41] 	at com.vencillio.rs2.entity.player.net.in.impl.ObjectPacket.handle(ObjectPacket.java:71)
[2017-09-20 01:19:41] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2017-09-20 01:19:41] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:270)
[2017-09-20 01:19:41] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2017-09-20 01:19:41] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2017-09-20 01:19:41] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2017-09-20 01:26:08] Failing to update Oe highscores. Database could not connect.
[2017-09-20 01:27:19] java.lang.ArrayIndexOutOfBoundsException: 0
[2017-09-20 01:27:19] 	at com.vencillio.core.util.Utility.randomElement(Utility.java:638)
[2017-09-20 01:27:19] 	at com.vencillio.rs2.content.CrystalChest.searchChest(CrystalChest.java:97)
[2017-09-20 01:27:19] 	at com.vencillio.rs2.entity.WalkToActions.finishObjectClick(WalkToActions.java:1860)
[2017-09-20 01:27:19] 	at com.vencillio.rs2.entity.WalkToActions$7.onDestination(WalkToActions.java:311)
[2017-09-20 01:27:19] 	at com.vencillio.core.task.impl.WalkToTask.execute(WalkToTask.java:39)
[2017-09-20 01:27:19] 	at com.vencillio.core.task.TaskQueue.queue(TaskQueue.java:117)
[2017-09-20 01:27:19] 	at com.vencillio.rs2.entity.WalkToActions.clickObject(WalkToActions.java:306)
[2017-09-20 01:27:19] 	at com.vencillio.rs2.entity.player.net.in.impl.ObjectPacket.handle(ObjectPacket.java:71)
[2017-09-20 01:27:19] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2017-09-20 01:27:19] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:270)
[2017-09-20 01:27:19] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2017-09-20 01:27:19] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2017-09-20 01:27:19] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2017-09-20 01:27:19] java.lang.ArrayIndexOutOfBoundsException: 0
[2017-09-20 01:27:19] 	at com.vencillio.core.util.Utility.randomElement(Utility.java:638)
[2017-09-20 01:27:19] 	at com.vencillio.rs2.content.CrystalChest.searchChest(CrystalChest.java:97)
[2017-09-20 01:27:19] 	at com.vencillio.rs2.entity.WalkToActions.finishObjectClick(WalkToActions.java:1860)
[2017-09-20 01:27:19] 	at com.vencillio.rs2.entity.WalkToActions$7.onDestination(WalkToActions.java:311)
[2017-09-20 01:27:19] 	at com.vencillio.core.task.impl.WalkToTask.execute(WalkToTask.java:39)
[2017-09-20 01:27:19] 	at com.vencillio.core.task.TaskQueue.queue(TaskQueue.java:117)
[2017-09-20 01:27:19] 	at com.vencillio.rs2.entity.WalkToActions.clickObject(WalkToActions.java:306)
[2017-09-20 01:27:19] 	at com.vencillio.rs2.entity.player.net.in.impl.ObjectPacket.handle(ObjectPacket.java:71)
[2017-09-20 01:27:19] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2017-09-20 01:27:19] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:270)
[2017-09-20 01:27:19] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2017-09-20 01:27:19] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2017-09-20 01:27:19] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2017-09-20 01:27:48] Failing to update Dbz highscores. Database could not connect.
[2017-09-20 01:34:22] Failing to update Grumpy highscores. Database could not connect.
[2017-09-20 02:26:39] Failing to update slayer highscores. Database could not connect.
[2017-09-20 02:57:54] Failing to update Grumpy highscores. Database could not connect.
[2017-09-20 04:29:14] Failing to update 69 highscores. Database could not connect.
[2017-09-20 04:29:37] Failing to update oi highscores. Database could not connect.
[2017-09-20 06:22:14] java.lang.ArrayIndexOutOfBoundsException: -1
[2017-09-20 06:22:14] 	at com.vencillio.rs2.content.bank.Bank.swap(Bank.java:294)
[2017-09-20 06:22:14] 	at com.vencillio.rs2.content.bank.Bank.depositFromNoting(Bank.java:222)
[2017-09-20 06:22:14] 	at com.vencillio.rs2.content.bank.Bank.clickButton(Bank.java:99)
[2017-09-20 06:22:14] 	at com.vencillio.rs2.entity.player.net.in.impl.ClickButtonPacket.handle(ClickButtonPacket.java:940)
[2017-09-20 06:22:14] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2017-09-20 06:22:14] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:270)
[2017-09-20 06:22:14] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2017-09-20 06:22:14] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2017-09-20 06:22:14] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2017-09-20 07:41:36] Failing to update Dbz highscores. Database could not connect.
[2017-09-20 07:52:18] Failing to update 69 highscores. Database could not connect.
[2017-09-20 08:22:28] java.lang.ArrayIndexOutOfBoundsException: 0
[2017-09-20 08:22:28] 	at com.vencillio.core.util.Utility.randomElement(Utility.java:638)
[2017-09-20 08:22:28] 	at com.vencillio.rs2.content.CrystalChest.searchChest(CrystalChest.java:97)
[2017-09-20 08:22:28] 	at com.vencillio.rs2.entity.WalkToActions.finishObjectClick(WalkToActions.java:1860)
[2017-09-20 08:22:28] 	at com.vencillio.rs2.entity.WalkToActions$7.onDestination(WalkToActions.java:311)
[2017-09-20 08:22:28] 	at com.vencillio.core.task.impl.WalkToTask.execute(WalkToTask.java:39)
[2017-09-20 08:22:28] 	at com.vencillio.core.task.TaskQueue.queue(TaskQueue.java:117)
[2017-09-20 08:22:28] 	at com.vencillio.rs2.entity.WalkToActions.clickObject(WalkToActions.java:306)
[2017-09-20 08:22:28] 	at com.vencillio.rs2.entity.player.net.in.impl.ObjectPacket.handle(ObjectPacket.java:71)
[2017-09-20 08:22:28] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2017-09-20 08:22:28] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:270)
[2017-09-20 08:22:28] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2017-09-20 08:22:28] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2017-09-20 08:22:28] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2017-09-20 08:48:36] Failing to update Zezima highscores. Database could not connect.
[2017-09-20 09:53:29] Failing to update Grumpy highscores. Database could not connect.
[2017-09-20 16:15:33] Failing to update Dbz highscores. Database could not connect.
[2017-09-20 17:50:47] java.lang.NumberFormatException: For input string: "10000\"
[2017-09-20 17:50:47] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2017-09-20 17:50:47] 	at java.lang.Long.parseLong(Unknown Source)
[2017-09-20 17:50:47] 	at java.lang.Long.parseLong(Unknown Source)
[2017-09-20 17:50:47] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:330)
[2017-09-20 17:50:47] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2017-09-20 17:50:47] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2017-09-20 17:50:47] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:270)
[2017-09-20 17:50:47] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2017-09-20 17:50:47] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2017-09-20 17:50:47] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2017-09-20 18:52:21] java.lang.ArrayIndexOutOfBoundsException: 0
[2017-09-20 18:52:21] 	at com.vencillio.core.util.Utility.randomElement(Utility.java:638)
[2017-09-20 18:52:21] 	at com.vencillio.rs2.content.CrystalChest.searchChest(CrystalChest.java:121)
[2017-09-20 18:52:21] 	at com.vencillio.rs2.entity.WalkToActions.finishObjectClick(WalkToActions.java:1860)
[2017-09-20 18:52:21] 	at com.vencillio.rs2.entity.WalkToActions$7.onDestination(WalkToActions.java:311)
[2017-09-20 18:52:21] 	at com.vencillio.core.task.impl.WalkToTask.execute(WalkToTask.java:39)
[2017-09-20 18:52:21] 	at com.vencillio.core.task.TaskQueue.queue(TaskQueue.java:117)
[2017-09-20 18:52:21] 	at com.vencillio.rs2.entity.WalkToActions.clickObject(WalkToActions.java:306)
[2017-09-20 18:52:21] 	at com.vencillio.rs2.entity.player.net.in.impl.ObjectPacket.handle(ObjectPacket.java:71)
[2017-09-20 18:52:21] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2017-09-20 18:52:21] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:270)
[2017-09-20 18:52:21] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2017-09-20 18:52:21] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2017-09-20 18:52:21] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2017-09-20 19:09:57] Failing to update Dbz highscores. Database could not connect.
[2017-09-20 19:20:10] Failing to update 69 highscores. Database could not connect.
[2017-09-20 19:23:23] Failing to update dbz highscores. Database could not connect.
[2017-09-20 19:24:37] Failing to update Dbz highscores. Database could not connect.
[2017-09-20 19:37:06] Failing to update Perm highscores. Database could not connect.
[2017-09-20 19:37:32] Failing to update Perm Fe highscores. Database could not connect.
[2017-09-20 19:40:47] Failing to update Dbz highscores. Database could not connect.
[2017-09-20 20:11:18] Failing to update Zezima highscores. Database could not connect.
[2017-09-20 20:11:18] Failing to update Boop highscores. Database could not connect.
[2017-09-20 20:17:43] java.lang.ArrayIndexOutOfBoundsException: 0
[2017-09-20 20:17:43] 	at com.vencillio.core.util.Utility.randomElement(Utility.java:638)
[2017-09-20 20:17:43] 	at com.vencillio.rs2.content.CrystalChest.searchChest(CrystalChest.java:97)
[2017-09-20 20:17:43] 	at com.vencillio.rs2.entity.WalkToActions.finishObjectClick(WalkToActions.java:1860)
[2017-09-20 20:17:43] 	at com.vencillio.rs2.entity.WalkToActions$7.onDestination(WalkToActions.java:311)
[2017-09-20 20:17:43] 	at com.vencillio.core.task.impl.WalkToTask.execute(WalkToTask.java:39)
[2017-09-20 20:17:43] 	at com.vencillio.core.task.TaskQueue.queue(TaskQueue.java:117)
[2017-09-20 20:17:43] 	at com.vencillio.rs2.entity.WalkToActions.clickObject(WalkToActions.java:306)
[2017-09-20 20:17:43] 	at com.vencillio.rs2.entity.player.net.in.impl.ObjectPacket.handle(ObjectPacket.java:71)
[2017-09-20 20:17:43] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2017-09-20 20:17:43] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:270)
[2017-09-20 20:17:43] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2017-09-20 20:17:43] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2017-09-20 20:17:43] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2017-09-20 20:18:00] java.lang.ArrayIndexOutOfBoundsException: 0
[2017-09-20 20:18:00] 	at com.vencillio.core.util.Utility.randomElement(Utility.java:638)
[2017-09-20 20:18:00] 	at com.vencillio.rs2.content.CrystalChest.searchChest(CrystalChest.java:121)
[2017-09-20 20:18:00] 	at com.vencillio.rs2.entity.WalkToActions.finishObjectClick(WalkToActions.java:1860)
[2017-09-20 20:18:00] 	at com.vencillio.rs2.entity.WalkToActions$7.onDestination(WalkToActions.java:311)
[2017-09-20 20:18:00] 	at com.vencillio.core.task.impl.WalkToTask.execute(WalkToTask.java:39)
[2017-09-20 20:18:00] 	at com.vencillio.core.task.TaskQueue.queue(TaskQueue.java:117)
[2017-09-20 20:18:00] 	at com.vencillio.rs2.entity.WalkToActions.clickObject(WalkToActions.java:306)
[2017-09-20 20:18:00] 	at com.vencillio.rs2.entity.player.net.in.impl.ObjectPacket.handle(ObjectPacket.java:71)
[2017-09-20 20:18:00] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2017-09-20 20:18:00] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:270)
[2017-09-20 20:18:00] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2017-09-20 20:18:00] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2017-09-20 20:18:00] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2017-09-20 20:18:18] java.lang.ArrayIndexOutOfBoundsException: 0
[2017-09-20 20:18:18] 	at com.vencillio.core.util.Utility.randomElement(Utility.java:638)
[2017-09-20 20:18:18] 	at com.vencillio.rs2.content.CrystalChest.searchChest(CrystalChest.java:97)
[2017-09-20 20:18:18] 	at com.vencillio.rs2.entity.WalkToActions.finishObjectClick(WalkToActions.java:1860)
[2017-09-20 20:18:18] 	at com.vencillio.rs2.entity.WalkToActions$7.onDestination(WalkToActions.java:311)
[2017-09-20 20:18:18] 	at com.vencillio.core.task.impl.WalkToTask.execute(WalkToTask.java:39)
[2017-09-20 20:18:18] 	at com.vencillio.core.task.TaskQueue.queue(TaskQueue.java:117)
[2017-09-20 20:18:18] 	at com.vencillio.rs2.entity.WalkToActions.clickObject(WalkToActions.java:306)
[2017-09-20 20:18:18] 	at com.vencillio.rs2.entity.player.net.in.impl.ObjectPacket.handle(ObjectPacket.java:71)
[2017-09-20 20:18:18] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2017-09-20 20:18:18] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:270)
[2017-09-20 20:18:18] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2017-09-20 20:18:18] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2017-09-20 20:18:18] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2017-09-20 20:18:24] java.lang.ArrayIndexOutOfBoundsException: 0
[2017-09-20 20:18:24] 	at com.vencillio.core.util.Utility.randomElement(Utility.java:638)
[2017-09-20 20:18:24] 	at com.vencillio.rs2.content.CrystalChest.searchChest(CrystalChest.java:121)
[2017-09-20 20:18:24] 	at com.vencillio.rs2.entity.WalkToActions.finishObjectClick(WalkToActions.java:1860)
[2017-09-20 20:18:24] 	at com.vencillio.rs2.entity.WalkToActions$7.onDestination(WalkToActions.java:311)
[2017-09-20 20:18:24] 	at com.vencillio.core.task.impl.WalkToTask.execute(WalkToTask.java:39)
[2017-09-20 20:18:24] 	at com.vencillio.core.task.TaskQueue.queue(TaskQueue.java:117)
[2017-09-20 20:18:24] 	at com.vencillio.rs2.entity.WalkToActions.clickObject(WalkToActions.java:306)
[2017-09-20 20:18:24] 	at com.vencillio.rs2.entity.player.net.in.impl.ObjectPacket.handle(ObjectPacket.java:71)
[2017-09-20 20:18:24] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2017-09-20 20:18:24] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:270)
[2017-09-20 20:18:24] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2017-09-20 20:18:24] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2017-09-20 20:18:24] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2017-09-20 20:19:43] java.lang.ArrayIndexOutOfBoundsException: 0
[2017-09-20 20:19:43] 	at com.vencillio.core.util.Utility.randomElement(Utility.java:638)
[2017-09-20 20:19:43] 	at com.vencillio.rs2.content.CrystalChest.searchChest(CrystalChest.java:97)
[2017-09-20 20:19:43] 	at com.vencillio.rs2.entity.WalkToActions.finishObjectClick(WalkToActions.java:1860)
[2017-09-20 20:19:43] 	at com.vencillio.rs2.entity.WalkToActions$7.onDestination(WalkToActions.java:311)
[2017-09-20 20:19:43] 	at com.vencillio.core.task.impl.WalkToTask.execute(WalkToTask.java:39)
[2017-09-20 20:19:43] 	at com.vencillio.core.task.TaskQueue.queue(TaskQueue.java:117)
[2017-09-20 20:19:43] 	at com.vencillio.rs2.entity.WalkToActions.clickObject(WalkToActions.java:306)
[2017-09-20 20:19:43] 	at com.vencillio.rs2.entity.player.net.in.impl.ObjectPacket.handle(ObjectPacket.java:71)
[2017-09-20 20:19:43] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2017-09-20 20:19:43] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:270)
[2017-09-20 20:19:43] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2017-09-20 20:19:43] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2017-09-20 20:19:43] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2017-09-20 20:52:37] Failing to update 69 highscores. Database could not connect.
[2017-09-20 20:52:55] java.lang.ArrayIndexOutOfBoundsException: 0
[2017-09-20 20:52:55] 	at com.vencillio.core.util.Utility.randomElement(Utility.java:638)
[2017-09-20 20:52:55] 	at com.vencillio.rs2.content.CrystalChest.searchChest(CrystalChest.java:97)
[2017-09-20 20:52:55] 	at com.vencillio.rs2.entity.WalkToActions.finishObjectClick(WalkToActions.java:1860)
[2017-09-20 20:52:55] 	at com.vencillio.rs2.entity.WalkToActions$7.onDestination(WalkToActions.java:311)
[2017-09-20 20:52:55] 	at com.vencillio.core.task.impl.WalkToTask.execute(WalkToTask.java:39)
[2017-09-20 20:52:55] 	at com.vencillio.core.task.TaskQueue.queue(TaskQueue.java:117)
[2017-09-20 20:52:55] 	at com.vencillio.rs2.entity.WalkToActions.clickObject(WalkToActions.java:306)
[2017-09-20 20:52:55] 	at com.vencillio.rs2.entity.player.net.in.impl.ObjectPacket.handle(ObjectPacket.java:71)
[2017-09-20 20:52:55] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2017-09-20 20:52:55] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:270)
[2017-09-20 20:52:55] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2017-09-20 20:52:55] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2017-09-20 20:52:55] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2017-09-20 20:52:57] java.lang.ArrayIndexOutOfBoundsException: 0
[2017-09-20 20:52:57] 	at com.vencillio.core.util.Utility.randomElement(Utility.java:638)
[2017-09-20 20:52:57] 	at com.vencillio.rs2.content.CrystalChest.searchChest(CrystalChest.java:97)
[2017-09-20 20:52:57] 	at com.vencillio.rs2.entity.WalkToActions.finishObjectClick(WalkToActions.java:1860)
[2017-09-20 20:52:57] 	at com.vencillio.rs2.entity.WalkToActions$7.onDestination(WalkToActions.java:311)
[2017-09-20 20:52:57] 	at com.vencillio.core.task.impl.WalkToTask.execute(WalkToTask.java:39)
[2017-09-20 20:52:57] 	at com.vencillio.core.task.TaskQueue.queue(TaskQueue.java:117)
[2017-09-20 20:52:57] 	at com.vencillio.rs2.entity.WalkToActions.clickObject(WalkToActions.java:306)
[2017-09-20 20:52:57] 	at com.vencillio.rs2.entity.player.net.in.impl.ObjectPacket.handle(ObjectPacket.java:71)
[2017-09-20 20:52:57] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2017-09-20 20:52:57] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:270)
[2017-09-20 20:52:57] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2017-09-20 20:52:57] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2017-09-20 20:52:57] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2017-09-20 21:04:33] Failing to update Dbz highscores. Database could not connect.
[2017-09-20 21:05:16] java.lang.IndexOutOfBoundsException: Index: 5, Size: 3
[2017-09-20 21:05:16] 	at java.util.LinkedList.checkElementIndex(Unknown Source)
[2017-09-20 21:05:16] 	at java.util.LinkedList.get(Unknown Source)
[2017-09-20 21:05:16] 	at com.vencillio.rs2.entity.player.net.in.impl.InterfaceAction.handle(InterfaceAction.java:88)
[2017-09-20 21:05:16] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2017-09-20 21:05:16] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:270)
[2017-09-20 21:05:16] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2017-09-20 21:05:16] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2017-09-20 21:05:16] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2017-09-20 21:05:16] java.lang.IndexOutOfBoundsException: Index: 5, Size: 3
[2017-09-20 21:05:16] 	at java.util.LinkedList.checkElementIndex(Unknown Source)
[2017-09-20 21:05:16] 	at java.util.LinkedList.get(Unknown Source)
[2017-09-20 21:05:16] 	at com.vencillio.rs2.entity.player.net.in.impl.InterfaceAction.handle(InterfaceAction.java:88)
[2017-09-20 21:05:16] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2017-09-20 21:05:16] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:270)
[2017-09-20 21:05:16] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2017-09-20 21:05:16] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2017-09-20 21:05:16] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2017-09-20 21:06:10] java.lang.IndexOutOfBoundsException: Index: 7, Size: 4
[2017-09-20 21:06:10] 	at java.util.LinkedList.checkElementIndex(Unknown Source)
[2017-09-20 21:06:10] 	at java.util.LinkedList.get(Unknown Source)
[2017-09-20 21:06:10] 	at com.vencillio.rs2.entity.player.net.in.impl.InterfaceAction.handle(InterfaceAction.java:88)
[2017-09-20 21:06:10] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2017-09-20 21:06:10] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:270)
[2017-09-20 21:06:10] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2017-09-20 21:06:10] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2017-09-20 21:06:10] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2017-09-20 21:06:10] java.lang.IndexOutOfBoundsException: Index: 7, Size: 4
[2017-09-20 21:06:10] 	at java.util.LinkedList.checkElementIndex(Unknown Source)
[2017-09-20 21:06:10] 	at java.util.LinkedList.get(Unknown Source)
[2017-09-20 21:06:10] 	at com.vencillio.rs2.entity.player.net.in.impl.InterfaceAction.handle(InterfaceAction.java:88)
[2017-09-20 21:06:10] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2017-09-20 21:06:10] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:270)
[2017-09-20 21:06:10] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2017-09-20 21:06:10] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2017-09-20 21:06:10] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2017-09-20 21:06:41] Failing to update Dbz highscores. Database could not connect.
[2017-09-20 21:07:22] Failing to update Dbzwd highscores. Database could not connect.
[2017-09-20 21:11:44] Failing to update Dbzwd highscores. Database could not connect.
[2017-09-20 21:45:46] Failing to update slayer highscores. Database could not connect.
[2017-09-20 22:04:55] Failing to update Zezima highscores. Database could not connect.
[2017-09-20 22:15:31] java.lang.IndexOutOfBoundsException: Index: 6, Size: 4
[2017-09-20 22:15:31] 	at java.util.LinkedList.checkElementIndex(Unknown Source)
[2017-09-20 22:15:31] 	at java.util.LinkedList.get(Unknown Source)
[2017-09-20 22:15:31] 	at com.vencillio.rs2.entity.player.net.in.impl.InterfaceAction.handle(InterfaceAction.java:88)
[2017-09-20 22:15:31] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2017-09-20 22:15:31] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:270)
[2017-09-20 22:15:31] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2017-09-20 22:15:31] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2017-09-20 22:15:31] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2017-09-20 22:15:31] java.lang.IndexOutOfBoundsException: Index: 6, Size: 4
[2017-09-20 22:15:31] 	at java.util.LinkedList.checkElementIndex(Unknown Source)
[2017-09-20 22:15:31] 	at java.util.LinkedList.get(Unknown Source)
[2017-09-20 22:15:31] 	at com.vencillio.rs2.entity.player.net.in.impl.InterfaceAction.handle(InterfaceAction.java:88)
[2017-09-20 22:15:31] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2017-09-20 22:15:31] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:270)
[2017-09-20 22:15:31] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2017-09-20 22:15:31] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2017-09-20 22:15:31] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2017-09-20 22:15:58] java.lang.IndexOutOfBoundsException: Index: 7, Size: 4
[2017-09-20 22:15:58] 	at java.util.LinkedList.checkElementIndex(Unknown Source)
[2017-09-20 22:15:58] 	at java.util.LinkedList.get(Unknown Source)
[2017-09-20 22:15:58] 	at com.vencillio.rs2.entity.player.net.in.impl.InterfaceAction.handle(InterfaceAction.java:88)
[2017-09-20 22:15:58] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2017-09-20 22:15:58] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:270)
[2017-09-20 22:15:58] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2017-09-20 22:15:58] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2017-09-20 22:15:58] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2017-09-20 22:15:58] java.lang.IndexOutOfBoundsException: Index: 7, Size: 4
[2017-09-20 22:15:58] 	at java.util.LinkedList.checkElementIndex(Unknown Source)
[2017-09-20 22:15:58] 	at java.util.LinkedList.get(Unknown Source)
[2017-09-20 22:15:58] 	at com.vencillio.rs2.entity.player.net.in.impl.InterfaceAction.handle(InterfaceAction.java:88)
[2017-09-20 22:15:58] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2017-09-20 22:15:58] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:270)
[2017-09-20 22:15:58] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2017-09-20 22:15:58] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2017-09-20 22:15:58] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2017-09-20 22:16:46] Failing to update Dbz highscores. Database could not connect.
[2017-09-20 22:16:46] Failing to update Boop highscores. Database could not connect.
[2017-09-20 22:16:46] Failing to update Perm highscores. Database could not connect.
[2017-09-20 22:16:47] Failing to update 69 highscores. Database could not connect.
